"""empty message

Revision ID: 3ada29b2eee3
Revises: 
Create Date: 2019-03-18 00:23:01.202543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ada29b2eee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_snippet', 'function_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('declarative_input_argument_item', 'argument_index',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('declarative_input_argument_item', 'declarative_input_item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('declarative_input_argument_item', 'input_type',
               existing_type=mysql.ENUM('Unset', 'VOID', 'INTEGER', 'STRING', 'ARRAY_INTEGER', 'ARRAY_STRING'),
               nullable=False)
    op.alter_column('declarative_input_item', 'output_value',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('function_argument', 'function_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('function_argument', 'function_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('declarative_input_item', 'output_value',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('declarative_input_argument_item', 'input_type',
               existing_type=mysql.ENUM('Unset', 'VOID', 'INTEGER', 'STRING', 'ARRAY_INTEGER', 'ARRAY_STRING'),
               nullable=True)
    op.alter_column('declarative_input_argument_item', 'declarative_input_item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('declarative_input_argument_item', 'argument_index',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('code_snippet', 'function_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
