"""empty message

Revision ID: 4d04909b3f66
Revises: 3ada29b2eee3
Create Date: 2019-03-18 00:30:31.831363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d04909b3f66'
down_revision = '3ada29b2eee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_snippet',
                  sa.Column('snippet_type',
                            sa.Enum('DEFAULT_TEMPLATE', 'MANUAL_TEMPLATE', name='snippettype'),
                            nullable=True)
                  )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_snippet', 'snippet_type')
    # ### end Alembic commands ###
